#!/bin/bash
# generate-specs.sh - Auto-generates OpenSpec specs from Python files

set -e

echo "🔍 Generating OpenSpec specs..."

# Scan for Python files (excluding node_modules, .git, __pycache__, venv)
find . -type f -name "*.py" \
  -not -path "./node_modules/*" \
  -not -path "./.git/*" \
  -not -path "./__pycache__/*" \
  -not -path "./venv/*" \
  -not -path "./.venv/*" | while read -r file; do
  
  # Get the base name without extension
  basename=$(basename "$file" .py)
  
  # Create spec directory if it doesn't exist
  mkdir -p .openspec/specs
  
  # Create .js spec file (OpenSpec expects JS format)
  spec_file=".openspec/specs/${basename}.js"
  
  # Skip if spec already exists and is up to date
  if [ -f "$spec_file" ] && [ "$file" -ot "$spec_file" ]; then
    echo "  ⏭️  Skipping $basename - spec is up to date"
    continue
  fi
  
  echo "  📝 Generating spec for $basename..."
  
  # Generate a basic OpenSpec spec
  cat > "$spec_file" <<EOF
// OpenSpec specification for ${basename}.py
// Auto-generated by generate-specs.sh

export const ${basename}Spec = {
  name: "${basename}",
  version: "1.0.0",
  description: "Auto-generated specification for ${basename}.py",
  type: "function",
  parameters: {
    type: "object",
    properties: {},
    required: []
  },
  returns: {
    type: "any",
    description: "Return value from the function"
  }
};

// Validation
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ${basename}Spec;
}
EOF
  
  # Validate spec using OpenSpec CLI
  if command -v openspec &> /dev/null; then
    openspec validate "$spec_file" || echo "  ⚠️  Validation warning for $spec_file"
  else
    echo "  ⚠️  openspec CLI not found, skipping validation"
  fi
done

echo "✅ OpenSpec specs generation complete"
echo "📁 Specs created in .openspec/specs/"